# ! Welcome to Numpy tutorial!

### Numpy as General purpose processing package.It provides a high performance multidimensional array objwct and tools for working with these arrays. It is Fundamental package for scientific computing

### Array - is a data structure that stores values of same data type.In python,this is main difference between arrays and lists.While python list is data structure that contains all data types,arrays contain only one data type

In [1]:
#import numpy
import numpy as np
a=np.array([1,2,3,4])
print(a)
# this is 1-d array as it it represented in([])
b=np.array([[2,4],[3,6]])
print(b)

[1 2 3 4]
[[2 4]
 [3 6]]


In [2]:
#some inbult functions 
print(a.size)  #returns total no of elements in a array
print(a.dtype) #to know a data type
print(type(b))
print(a.shape) #when there is 1-d array it always gives values of only items (shape=rows,columns)
print(a.ndim)  #specifies 1-d or 2-d

4
int32
<class 'numpy.ndarray'>
(4,)
1


In [3]:
#Multinested array
a=[1,2,3,4,5]
b=[5,3,6,7,8]
c=[2,3,6,1,9]
arr=np.array([a,b,c])
print(arr)
n=arr.shape
print(n)
arr.reshape(5,3)
arr

[[1 2 3 4 5]
 [5 3 6 7 8]
 [2 3 6 1 9]]
(3, 5)


array([[1, 2, 3, 4, 5],
       [5, 3, 6, 7, 8],
       [2, 3, 6, 1, 9]])

In [12]:
a=np.zeros((3,4))
print(a)
a=np.ones((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
c=np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [5]:
##Random values
#interger random values
#pixel values btn 0-255
i=np.random.rand(3,3)#picks a random values
print(i)
c=np.random.randn(4,4)#returns with standard distribution
print(c)
n=np.random.randint(0,50,(4,5))
print(n)

[[0.98767003 0.25996386 0.53238144]
 [0.59811888 0.61282545 0.86155381]
 [0.25814203 0.06917984 0.38056114]]
[[-1.14138073  0.56017554 -1.65885828  0.01532306]
 [ 0.32636652  2.64130208  0.1702747  -0.74610242]
 [-0.06682769  1.93056611 -1.05658824  0.49037194]
 [ 0.74716199 -1.48085689 -1.95573144  0.02861054]]
[[38  7 45 34 35]
 [47 38 26 43 25]
 [ 0 32  3 19 19]
 [40 17 47 42 23]]


In [14]:
#linspace
import numpy as np

b=np.linspace(0,30,4)
print(b)

[ 0. 10. 20. 30.]


In [6]:
#arange=start:stop:step
p=np.arange(0,40)
print(p)
b=np.arange(0,50,5)#with step
print(b)

#linespace  start;stop:no of values
p=np.linspace(1,10,50)
print(p)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0  5 10 15 20 25 30 35 40 45]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [7]:
#mathematical operations
b=np.array([[4,7],[9,3]])
print(b+1)#1 added to each element
print(b-2)# 2 is substracted
print(b*3)# multiply by 3 to each element
print(b/4)#divide
print(b**2)



[[ 5  8]
 [10  4]]
[[2 5]
 [7 1]]
[[12 21]
 [27  9]]
[[1.   1.75]
 [2.25 0.75]]
[[16 49]
 [81  9]]
[[2.         2.64575131]
 [3.         1.73205081]]
[[-0.7568025   0.6569866 ]
 [ 0.41211849  0.14112001]]
[[-0.65364362  0.75390225]
 [-0.91113026 -0.9899925 ]]
[[ 1.15782128  0.87144798]
 [-0.45231566 -0.14254654]]
23
3
9
[4 3]
[7 9]
[4 3]
[0. 0. 0. 0.]


In [15]:
print(np.sqrt(b))  #sqrt of each number
print(np.sin(b))  #sin function of b
print(np.cos(b)) #cosine
print(np.tan(b))  #tan
print(np.sum(b))
print(np.min(b))
print(np.max(b))

[0.         3.16227766 4.47213595 5.47722558]
[ 0.         -0.54402111  0.91294525 -0.98803162]
[ 1.         -0.83907153  0.40808206  0.15425145]
[ 0.          0.64836083  2.23716094 -6.4053312 ]
60.0
0.0
30.0


In [22]:
import numpy as np
a=np.array([[1,2],[3,4]])

print(a)
#col = 0  axis=0 is known as col
print(np.min(a,axis=0))
print(np.max(a,axis=0))
#row
print(np.min(a,axis=1))
print(np.max(a,axis=1))


[[1 2]
 [3 4]]
[1 2]
[3 4]
[1 3]
[2 4]


In [23]:
#sort
a=np.array([[5,6],[4,2]])
print(a)

print(np.sort(a)) #defalut change in row
print(np.sort(a,axis=0))

[[5 6]
 [4 2]]
[[5 6]
 [2 4]]
[[4 2]
 [5 6]]


### sort,matmul and dot 

In [25]:
a=np.array([[5,6],[7,9]])
print(a)
o=(np.sort(a,axis=0))
print(o)
b=np.array([[1,1],[1,1]])
y=np.array([[1,1],[1,1]])
print(np.matmul(b,y))
print(np.dot(b,y))

[[5 6]
 [7 9]]
[[5 6]
 [7 9]]
[[2 2]
 [2 2]]
[[2 2]
 [2 2]]


In [26]:
#matrix transpose row to col and col to row
a=np.array([[5,6],[4,2]])
b=np.array([[1,2],[3,4]])
print(a.T)
print(b.T)

[[5 4]
 [6 2]]
[[1 3]
 [2 4]]


In [27]:
a=np.linspace(1,20,12)
print(a)
print(a.shape)
a=a.reshape(3,4)
print(a)
print(a.shape)

[ 1.          2.72727273  4.45454545  6.18181818  7.90909091  9.63636364
 11.36363636 13.09090909 14.81818182 16.54545455 18.27272727 20.        ]
(12,)
[[ 1.          2.72727273  4.45454545  6.18181818]
 [ 7.90909091  9.63636364 11.36363636 13.09090909]
 [14.81818182 16.54545455 18.27272727 20.        ]]
(3, 4)


In [9]:
o=np.zeros((5,6))
print(o)
n=o.flatten()  #2d is converted to 1-d
print(n)
a=np.random.randint(1,10,(3,3))
print(a)
k=a.reshape(1,-1)   #shows as total rows
print(k)
o=a.reshape(-1,1)  #shows total as columns
print(o)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[[2 5 1]
 [1 8 6]
 [8 8 4]]
[[2 5 1 1 8 6 8 8 4]]
[[2]
 [5]
 [1]
 [1]
 [8]
 [6]
 [8]
 [8]
 [4]]


In [29]:
a=np.random.randint(1,10,(3,3))
print(a)
a=a.reshape(1,-1) # in this statment required 1 row fixed and many col
print(a)

[[1 1 1]
 [6 5 7]
 [5 6 9]]
[[1 1 1 6 5 7 5 6 9]]


### SLICING

In [32]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[1:2,1:])
print(y[::2,1:2])
print(y[1,1])
print(a[0::2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]]
[[2]
 [8]]
5
[[8 7 2]
 [5 6 5]]


In [33]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[::2,::2])
print(b[1:2,1:2])
print(b[1,1])
print(b[0::2,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [7 9]]
[[5]]
5
[[1 2 3]
 [7 8 9]]


In [11]:
val=2
p=y[y<val]
print(p)
o=y/2
print(o)
i=y%2
print(i)
l=y*2
print(l)
np.ones(4,dtype=float)
np.ones((2,5),dtype=int)

[1]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])